name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1  # Use latest version
      with:
        cmake-version: 'latest'  # Use the latest version

    #- name: Configure and build
      #run: |
        #mkdir build
        #cd build
        #cmake ..
        #cmake --build .
        #ctest --output-on-failure
