name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.14.2  # Use latest version
      with:
        cmake-version: 'latest'  # Use the latest version

    - name: Install fmt
      run: |
        sudo apt-get update
        sudo apt-get install -y libfmt-dev

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest --output-on-failure
